version: "3.9"

networks:
  internal_nw:
    name: internal_nw
    driver: bridge

services:
  database:
    container_name: database-node
    image: cockroachdb/cockroach:v22.2.0
    command: start-single-node --insecure --http-addr 0.0.0.0
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "26257:26257"
      - "8080:8080"
    networks:
      - internal_nw

  broker:
    image: rabbitmq:3.8-management
    container_name: rabbitmq-node
    ports:
      - 0.0.0.0:5672:5672
      - 0.0.0.0:15672:15672
    volumes:
      - "./config/test_setup.sh:/dev/test_setup.sh"
      - "./config/definitions.json:/etc/rabbitmq/definitions.json"
      - "./config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_NODE_IP_ADDRESS=0.0.0.0
      - NODE_IP_ADDRESS=0.0.0.0
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit loopback_users "none"
    command: >
      sh -c "rabbitmq-server"
    networks:
      - internal_nw

  backend:
    build:
      context: ../phase_3/investor_bulletin
      dockerfile: backend/Dockerfile
    container_name: backend-node
    hostname: backend
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - database
    environment:
      - RAPID_API_KEY=
      - RAPID_API_HOST=twelve-data1.p.rapidapi.com
      - DATABASE_URL=cockroachdb://root@database:26257/defaultdb?sslmode=disable
      - RABBITMQ_URL=amqp://guest:guest@broker:5672/
      - MESSAGING_URL=http://messaging:8001
      - MESSAGING_ROUTE=messaging
    networks:
      - internal_nw

  messaging:
    build:
      context: ../phase_3/investor_bulletin
      dockerfile: core/Dockerfile
    container_name: messaging-node
    ports:
      - "8001:8001"
    restart: always
    depends_on:
      - database
      - broker
      - backend
    environment:
      - RABBITMQ_HOST=broker
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_PORT=5672
      - BACKEND_URL=http://backend:8000
      - ALERTS_ROUTE=alerts
      - ALERT_RULES_ROUTE=alert-rules
    networks:
      - internal_nw

  subscription:
    build:
      context: ../phase_3/investor_bulletin
      dockerfile: event_subscriber/Dockerfile
    container_name: subscription-node
    restart: always
    depends_on:
      - broker
      - messaging
    environment:
      - BROKER=broker
      - BROKER_PORT=5672
    networks:
      - internal_nw

  worker:
    build:
      context: ../phase_3/investor_bulletin
      dockerfile: worker/Dockerfile
    container_name: worker-node
    restart: always
    depends_on:
      - broker
      - messaging
    environment:
      - BROKER_URL=amqp://guest:guest@broker:5672/
      - RESULTS_URL=rpc://broker
      - BACKEND_URL=http://backend:8000
      - MARKET_PRICES=market-prices
      - ALERTS_ROUTE=alerts
      - ALERT_RULES_ROUTE=alert-rules
      - MESSAGING_ROUTE=messaging

    networks:
      - internal_nw

  scheduler:
    build:
      context: ../phase_3/investor_bulletin
      dockerfile: worker/beat-scheduler/Dockerfile
    container_name: beat-node
    restart: always
    depends_on:
      - broker
      - messaging
    environment:
      - BROKER_URL=amqp://guest:guest@broker:5672/
    networks:
      - internal_nw
